Documentation:
  Enabled: false
Metrics/LineLength:
  IgnoredPatterns: ['(\A|\s)#']
  Max: 100
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/MethodLength:
  Max: 35
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false